### ISSUE TITLE
Cookies fail to update with Phantomjs 2.1.1

### ISSUE THREAD

**Issue by 2tim** [cryzed/Selenium-Requests#11]
I tried using an older version of phantomjs (1.9.2 and 1.9.8) from another issue but the site seems to reject the cookies from that attempt and redirects. I switched to phantomjs 2.1.1 and the request seems to get the response I want but never returns because it times out while trying to update the phantomjs cookies. Here is the code that it seems to fail on:

```
        # Some WebDrivers (PhantomJS) take some time until the new window
        # handle has loaded and cookies can be set
        start = time.time()
        while page_load_timeout < 0 or time.time() - start <= page_load_timeout:
            try:
                self.add_cookie(cookie_dict)
                break
            except WebDriverException:
                pass
        else:
            raise TimeoutException('page took too long to load')
```

This is lines 221 - 231 of request.py of the latest version available for install through pip.  On line 211 I have:

```
    response = self._seleniumrequests_session.request(method, url, **kwargs)
```

With phantomjs 2.1.1 the response.text looks good but with phantomjs 1.9.8 it seems to redirect me to the start page which leads me to expect the cookies don't look right. Please let me know if you need more info. I can provide a sample.

**Comment by 2tim** [comment]
I was able to dig a little deeper with the debugger and found that it fails to set the cookies with this message:

**Comment by cryzed** [comment]
I'll take a look at these issues as soon as I find time. Thank you for reporting them!

**Comment by 2tim** [comment]
Thanks, I also added a pull request. I made a change that enabled phantomjs
2.1.1 but couldn't get 1.9.8 to work. This package is a great idea. Thanks
for it. I would like to help more if I can with phantomjs support either by
me or someone on my team.

On Oct 26, 2016, at 11:26 PM, Chris Braun <notifications@github.com> wrote:

I'll take a look at these issues as soon as I find time. Thank you for
reporting them!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cryzed/Selenium-Requests/issues/11#issuecomment-256543627>,
or mute the thread

**Comment by cryzed** [comment]
A sample of a scenario where this happens would be great, if you could provide one. I might be able to simply catch the `WebDriverException` and inspect it for the actual error message -- if it is: "Can only set Cookies for the current domain" and the current driver is PhantomJS, one could simply use the fix you provided in your pull request.

**Comment by 2tim** [comment]
I used the example from the readme and replaced firefox with phantomjs. It
failed before the fix on my Mac, El Capitan, Python 2.7.10 phantomjs 2.1.1.

On Oct 28, 2016, at 10:44 AM, Chris Braun <notifications@github.com> wrote:

A sample of a scenario where this happens would be great, if you could
provide one. I might be able to simply catch the WebDriverException and
inspect it for the actual error message -- if it is: "Can only set Cookies
for the current domain" and the current driver is PhantomJS, one could
simply use the fix you provided in your pull request.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cryzed/Selenium-Requests/issues/11#issuecomment-256954065>,
or mute the thread

**Comment by cryzed** [comment]
So the issue you are experiencing with PhantomJS is probably this: [addCookie always returns false in v2.1.1](https://github.com/ariya/phantomjs/issues/14047). I removed old workaround code for various PhantomJS-related bugs (which seemingly have been fixed) and added new workaround code for the new bugs, including this one.

The test suite seems to currently pass repeatedly without failures on my end -- If you could try the current code using your scenario and report back the results, that would be great. If it works I'll fix up the remaining things and prepare a new release.

You can install the version from this repository like this:

`pip install https://github.com/cryzed/Selenium-Requests/archive/master.zip`

**Comment by cryzed** [comment]
Any update on this?

**Comment by stevezau** [comment]
any updates on this? I'm hitting this issue as well.
