### ISSUE TITLE
module.__init__() takes at most 2 arguments (3 given)

### ISSUE THREAD

**Issue by imlordeyaya** [cryzed/Selenium-Requests#14]
Hello when im trying to run this code:
    `from seleniumrequests.request import RequestMixin
    from selenium import webdriver
    class SpecialDriver(webdriver, RequestMixin):
        pass
    custom_webdriver = SpecialDriver()
    response = custom_webdriver.request('GET', 'https://www.google.com/')
    print(response)`
I get error: module.__init__() takes at most 2 arguments (3 given)

**Comment by cryzed** [comment]
Please follow the example in the `README` -- you have to import and subclass a specific webdriver, you are attempting to subclass a module.
