### ISSUE TITLE
Doesn't work with PhantomJS

### ISSUE THREAD

**Issue by eviled23** [cryzed/Selenium-Requests#18]
Hi, I was trying to use PhantomJs, however I'm keep on getting this error.

> response = webdriver.request('GET', 'https://www.google.com/')
>TypeError: request() missing 1 required positional argument: 'url'

**Comment by Mattwmaster58** [comment]
I think you need to use it like this: `response = webdriver.request(method='GET', url='https://www.google.com/')`

but I'm not sure becuase that gives me this error `TypeError: request() missing 1 required positional argument: 'self'`

**Comment by cryzed** [comment]
If you get this type of error, it indicates that you didn't instantiate the class into an object and simply attempted to call the method directly on the class -- it's not a static method, that won't work. Follow the example in the `README` or post your full code.
