### ISSUE TITLE
Error while trying to use proxy 

### ISSUE THREAD

**Issue by ventum86** [cryzed/Selenium-Requests#20]
Hi , your library is great ! But can i used it with proxy ? Is there some example how it can be used ? im using chromedriver and tried to add chrome_options , driver works OK but when im trying to make a request call im getting  pop up tab with ERR_ACCESS_DENIED .

Thanks in advance.
Regards 
Aleksandr

**Comment by cryzed** [comment]
That is the response your browser gets from the proxy -- this is unrelated to Selenium-Requests. You have misconfigured the connection details for the proxy server in some way using the `chrome_options` dict. Make sure that you have specified the correct proxy type/login credentials and if the proxy server is even reachable.
