### ISSUE TITLE
 Infinite loop and didn't automatically close the tab

### ISSUE THREAD

**Issue by botdigit** [cryzed/Selenium-Requests#27]
Selenium-Requests sometime fall into a infinite loop . On a windows machine while requesting http://shopeverythingbaby.com/7am-enfant-polar-warmmuffs-bordeaux.html . It just open a normal  second (auto close) tab but it didn't close it automatically  . But on linux machine using ubuntu 16.04 it works fine .

Below are the logs from Scrapy 

08/15/2018 18:08:04 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://127.0.0.1:52622/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "goog:chromeOptions":

{"extensions": [], "args": ["--disable-infobars", "--start-maximized"]}
}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "goog:chromeOptions":

{"extensions": [], "args": ["--disable-infobars", "--start-maximized"]}
}}
08/15/2018 18:08:04 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): 127.0.0.1:52622
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "POST /session HTTP/1.1" 200 867
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/window_handles {"sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "GET /session/eaddf464138563424cbec27fc53a37d2/window_handles HTTP/1.1" 200 113
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/window_handle {"sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "GET /session/eaddf464138563424cbec27fc53a37d2/window_handle HTTP/1.1" 200 111
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/execute {"script": "window.open('http://127.0.0.1:52716/');", "args": [], "sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "POST /session/eaddf464138563424cbec27fc53a37d2/execute HTTP/1.1" 200 72
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/window_handle {"sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "GET /session/eaddf464138563424cbec27fc53a37d2/window_handle HTTP/1.1" 200 111
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/window_handles {"sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "GET /session/eaddf464138563424cbec27fc53a37d2/window_handles HTTP/1.1" 200 113
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/url {"sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "GET /session/eaddf464138563424cbec27fc53a37d2/url HTTP/1.1" 200 76
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/window_handle {"sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "GET /session/eaddf464138563424cbec27fc53a37d2/window_handle HTTP/1.1" 200 111
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/window_handle {"sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "GET /session/eaddf464138563424cbec27fc53a37d2/window_handle HTTP/1.1" 200 111
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/url {"sessionId": "eaddf464138563424cbec27fc53a37d2"}
08/15/2018 18:08:07 [urllib3.connectionpool] DEBUG: http://127.0.0.1:52622 "GET /session/eaddf464138563424cbec27fc53a37d2/url HTTP/1.1" 200 76
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
08/15/2018 18:08:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:52622/session/eaddf464138563424cbec27fc53a37d2/window_handles {"sessionId": "eaddf464138563424cbec27fc53a37d2"} ....

**Comment by danelewis** [comment]
I have the same issue. No problem on MacOS, but when my client runs it on his Windows Machine it occasionally hangs with the Chrome Browser at 127.0.0.1:5XXX.

There is also a question on Stack Exchange detailing the same issue - https://stackoverflow.com/questions/54460567/selenium-post-request-opens-a-new-tab-in-chrome-and-trys-to-reach-127-0-0-15xxx

**Comment by cryzed** [comment]
It looks like Chrome is freezing during requesting the window handles. This issue suspiciously sounds like [this](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1077) which I reported ages ago. Is it possible you are using an old Chrome version on Windows?
