### ISSUE TITLE
How to use with pytest-selenium?

### ISSUE THREAD

**Issue by hasufell** [cryzed/Selenium-Requests#29]
[pytest-selenium](https://github.com/pytest-dev/pytest-selenium) provides a "selenium" fixture. I don't see how this would work with seleniumrequests.

**Comment by hasufell** [comment]
Why was this issue closed?

**Comment by cryzed** [comment]
Because this is not an issue, nor is it related to Selenium-Requests; It's a question on how to use pytest. You'll have more luck asking in the pytest avenues.

**Comment by hasufell** [comment]
> Because this is not an issue, nor is it related to Selenium-Requests; It's a question on how to use pytest. You'll have more luck asking in the pytest avenues, I don't know how to use pytest fixtures.

Sure, it's usually considered better practice though to close issues with an explanation.
