### ISSUE TITLE
Add headers keyword argument to request method

### ISSUE THREAD

**Issue by ckcollab** [cryzed/Selenium-Requests#3]
First of all: thanks for releasing this! Really appreciate the hard work.

Instead of using a headers global variable, why don't we pass it as a keyword argument on the request method?

**Comment by ckcollab** [comment]
Or maybe I missed something! I forked this + made the changes then as I was writing a test I noticed:
```python
response = webdriver.request('GET', echo_header_server, headers={'extra': 'header'}, cookies={'extra': 'cookie'})```

**Comment by cryzed** [comment]
The global headers variable is used by the HTTPRequestHandler to get the default headers sent by the browser controlled by the webdriver. These are later automatically merged with headers you pass in when using the request method, in your example here: ```headers={'extra': 'header'}```.

**Comment by ckcollab** [comment]
> It's actually one of the "advertised" features

Huh? I couldn't find any reference to the extra kwargs anywhere outside of tests? Also might be useful to add it to the function signature/doc/something?

**Comment by cryzed** [comment]
The first line in the features section of the readme:
> Sends the "default" HTTP headers for the chosen WebDriver

Also even before that in the description:
> Before the actual request is made, a local HTTP server is started that serves a single request made by the webdriver instance to get the "standard" HTTP request headers sent by this webdriver; these are cached (only happens once during its lifetime) and later used in conjunction with the Requests library to make the requests look identical to those that would have been sent by the webdriver.

**Comment by ckcollab** [comment]
Yeah I saw that, even after reading that (and lack of familiarity with how requests does headers) I didn't realize that keyword argument was an option. Just thought it'd be helpful to add that information somewhere so someone in my predicament doesn't have to go through as much trouble.
