### ISSUE TITLE
Cant get headers into current page

### ISSUE THREAD

**Issue by alex-pancho** [cryzed/Selenium-Requests#30]
Step to reproduce:
1. create webdriver ( from seleniumrequests import Chrome)
2. with selenium login to website, do some action.
3. send request for get some data
```
def get_digital_pass(context):
    c = context
    print("="*10)
    response =  c.browser.request('POST', "mainwebsiteaddr"+'/authentication/challenge',
                 data={"user.document.id": c.id})
    print("challenge hd", response.headers)
    print("challenge ct", response.content)
```

But from server side my request and response looks as anonimus.
This is bug, or may be i do some wrong, please, help me

ADD: Also, may be important, that the site is protected from [CSRF](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29)

**Comment by cryzed** [comment]
I have no idea what you mean by anonymous -- possibly the cookies you expect to see here, are set via JavaScript.
