### ISSUE TITLE
There is an infinite loop problem due to windows firewall

### ISSUE THREAD

**Issue by Onewquant** [cryzed/Selenium-Requests#31]
when I executed a request with turned off windows firewall, it worked. 

However, when I turned on the firewall,  the selenium-request module didn't work.

I think it because the port for request are banned by firewall.

Could you fix it? 

I really appreciate this valuable package

**Comment by cryzed** [comment]
If you don't allow connection from the local host to local ports, then your firewall is configured strangely. Whitelist/accept the connection request that is made by the script. I don't know how to configure a Windows firewall.
