### ISSUE TITLE
TypeError: 'NoneType' object does not support item deletion

### ISSUE THREAD

**Issue by LuciferJack** [cryzed/Selenium-Requests#36]
`  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/seleniumrequests/request.py", line 141, in request
    self._seleniumrequests_session.headers = get_webdriver_request_headers(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/seleniumrequests/request.py", line 83, in get_webdriver_request_headers
    del headers_['host']
TypeError: 'NoneType' object does not support item deletion`

in the source code:

```
if webdriver.current_window_handle != original_window_handle:
    webdriver.switch_to.window(original_window_handle)

global headers
headers_ = headers
headers = None

# Remove the host header, which will simply contain the localhost address
# of the HTTPRequestHandler instance
del headers_['host']
return headers_

```

why headers = None and global headers ,but last del headers_

**Comment by cryzed** [comment]
`headers` is a global variable which is initially assigned to in `HTTPRequestHandler.do_GET`, to get the webdriver's default request headers. In `get_webdriver_request_headers` we then get this value, delete the `host` header and use it from the on on. We assign `headers = None` then, because it will never be needed or used anymore.

It's a mystery to me how you are getting this error if you are using my code in an unmodified state.

**Comment by cryzed** [comment]
I'm closing this for now, let me know if the issue persists after making sure that you use unmodified code.

**Comment by LuciferJack** [comment]
> `headers` is a global variable which is initially assigned to in `HTTPRequestHandler.do_GET`, to get the webdriver's default request headers. In `get_webdriver_request_headers` we then get this value, delete the `host` header and use it from the on on. We assign `headers = None` then, because it will never be needed or used anymore.
> 
> It's a mystery to me how you are getting this error if you are using my code in an unmodified state.

this happen when use multithreading env ，because the `global header`
