### ISSUE TITLE
can't penetrate cloudflare v2

### ISSUE THREAD

**Issue by KebabLord** [cryzed/Selenium-Requests#41]
I guess this module simply passes headers and cookies to requests whereas cloudflare v2 protection needs you to decrypt a javascript cipher in order to verify that you're human. Since requests can't render DOM it's failing.

**Comment by KebabLord** [comment]
project seems dead and there is no solution to this problem unless maintainer rewrites the whole request system to use jquery.get instead.

**Comment by raddup** [comment]
you need to use custom webdriver https://github.com/ultrafunkamsterdam/undetected-chromedriver
