### ISSUE TITLE
ImportError: cannot import name 'RequestMixin'

### ISSUE THREAD

**Issue by gavrielrh** [cryzed/Selenium-Requests#44]
Hi 😄 
Thanks for writing this library! It's a neat solution, and it made doing some cookie based auth a breeze.

Recently (yesterday? I just noticed it today, but I see there was a release yesterday) I started running into the following error in an automated test pipeline that utilizes selenium & selenium-requests.

```
from seleniumrequests.request import RequestMixin
ImportError: cannot import name 'RequestMixin' from 'seleniumrequests.request'
```

The project being run in the pipeline was using `selenium-requests = "^1.3"` to ensure compatibility, but I've since had to lock it to `selenium-requests = "1.3"` to resolve the import problem.

I'd love to be able to rely on the minor version again, but having breaking changes come in a PATCH version makes me nervous.

Going forward, would it be possible to bump the major version if there is going to be a significant change like dropping support for a version of Python / something incompatible? 

Thank you!! 🙇

**Comment by cryzed** [comment]
I will be more careful in the future, sorry. However your error doesn't make sense to me:

`from seleniumrequests.request import RequestsSessionMixin` should still work.

I didn't rename the mixin class.

**Comment by cryzed** [comment]
I just made a 1.3.3 release which added some code to add backwards-compatibility to the previous point release. Again, sorry for breaking this, despite many years of writing code I actually only rarely publish any.

(For what it's worth, the Python 2 compatibility I deprecated in addition, couldn't have been working for a while now).

**Comment by gavrielrh** [comment]
No worries! I really appreciate what you've been working on. I know how difficult it can be to manage these sort of things :)
Thank you for the quick response!

**Comment by gavrielrh** [comment]
Forgot to mention, you might want to update your README if you plan on deprecating that mixin name 😄 

Right now it still shows:
```python
# More complex usage, using a WebDriver from another Selenium-related module:
from seleniumrequests.request import RequestMixin
```

**Comment by cryzed** [comment]
Thanks!
