### ISSUE TITLE
It keeps loading the Andriod.

### ISSUE THREAD

**Issue by cfatduck** [cryzed/Selenium-Requests#46]
ImportError: cannot import name 'Android' from 'selenium.webdriver' 

Sample Code:
from seleniumrequests import Chrome  
webdriver = Chrome() 
response = webdriver.request('GET', 'https://www.google.com/') 
print(response)

**Comment by cryzed** [comment]
I'm not sure what you are doing or what your specific error is -- the `ImportError` itself, or the fact that apparently the Android webdriver isn't loading. Please recreate the issue and attach more useful information next time and steps to reproduce.
