### ISSUE TITLE
PhantomJS no longer supported in Selenium

### ISSUE THREAD

**Issue by NickScottKortical** [cryzed/Selenium-Requests#47]
Hi,

I was wondering if there are any plans to remove PhantomJS from this package, the newest versions of Selenium do not include it and so this package is not compatible with selenium 4+ (as you say this package is only tested on selenium 3.0.1).

Here is an issue on SeleniumHQ github discussing removal of it: https://github.com/SeleniumHQ/selenium/issues/5295

and in the current version you get an error on import as PhantomJs is no longer part of selenium.webdriver
```
from selenium.webdriver import Firefox, Chrome, Ie, Opera, Safari, PhantomJS, Android, Remote
E   ImportError: cannot import name 'PhantomJS' from 'selenium.webdriver'
```

I am happy to try and create a PR that removes it if that is helpful.

Thanks

Nick

**Comment by NickScottKortical** [comment]
Looking into the selenium 4.0.0+ change logs its more than just PhantomJS that is no longer supported: 
```
* Delete support for Blackberry Driver
* Delete PhantomJS capabilities
* Delete Android Driver support
```

I have some changes locally, but im unsure how to run the tests, currently i get the message:
 `Skipped: WebDriver not available`

which i imagine means i need the webdrivers somewhere?

**Comment by cryzed** [comment]
@NickScottKortical this should be fixed in the current release.
