### ISSUE TITLE
use with sharepy?

### ISSUE THREAD

**Issue by wendellwt** [cryzed/Selenium-Requests#57]
How can I use [sharepy](https://pypi.org/project/sharepy/) to make a connection within selenium using `selenium-requests`?

Should the sharepy connection mechanism be put inside a `MyCustomWebDriver`, use it to make the connection, and then use (regular) selenium for all of the responses (which would be request objects)?

Or should the 'main' connection be sharepy, and let sharepy get a `requests.models.Response `and then somehow pass that to selenium using `selenium-requests`?

**Comment by cryzed** [comment]
Sorry, I don't know sharepy.
