### ISSUE TITLE
Solution for using Selenium Requests with webdriver Options?

### ISSUE THREAD

**Issue by wilczynskiwm** [cryzed/Selenium-Requests#59]
Is there any way to use browser options with selenium requests?

```
from seleniumrequests.request import RequestsSessionMixin
from selenium.webdriver import Chrome, ChromeOptions

options = ChromeOptions()
options.add_argument("--headless")

class MyCustomWebDriver(RequestsSessionMixin, Chrome(options=options)):
    pass
```

`TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

**Comment by aweddle2** [comment]
I think you need to pull the Chrome object from seleniumrequests package rather than selenium.  So

```
from seleniumrequests.request import RequestsSessionMixin, Chrome
from selenium.webdriver import ChromeOptions

options = ChromeOptions()
options.add_argument("--headless")

class MyCustomWebDriver(RequestsSessionMixin, Chrome(options=options)):
    pass
```

**Comment by cryzed** [comment]
What you are doing doesn't make sense to me: you are trying to inherit from a class instance (`Chrome(options=options)`) instead of the class `Chrome`.

`options` [is an argument to the class constructor](https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.chrome.webdriver) (`__init__()`) and should be passed like it:

```python
from seleniumrequests.request import RequestsSessionMixin
from selenium.webdriver import Chrome, ChromeOptions

options = ChromeOptions()
options.add_argument("--headless")

class MyCustomWebDriver(RequestsSessionMixin, Chrome):
    pass


my_custom_webdriver_instance = MyCustomWebDriver(options=options)
```
